version: "3"

services:
  php:
    image: php:8.1.18-apache
    container_name: meu-php
    ports:
      - "8080:80"
    volumes:
      - /home/welitonlima/Documentos/algorithms-and-data-structure/:/var/www/html
